### ISSUE TITLE
[Feature] Use classes instead of structs and impliment Finalizer and IDisposable.

### ISSUE THREAD

**Issue by Shadowblitz16** [MrScautHD/Raylib-CSharp#11]
**Is your feature request related to a problem? Please describe.**
It seems you still use structs which don't have the ability to finalize.

**Describe the solution you'd like**
Move Raylib-CSharp structs to classes and implement IDisposable

**Describe alternatives you've considered**
Idk

**Additional context**
It could be implemented as a base class called Disposable.
here is the code...

```cs
public abstract class Disposable : IDisposable
{
    bool _disposed = false;

     ~Disposable()
    {
        Dispose();
    }
     
    protected virtual void OnDispose()
    {
    }

     public void Dispose()
    {
        if (_disposed) return;
        _disposed = true;
        
        OnDispose();

        GC.SupressFinalize(this);
    }
}
```

**Comment by MrScautHD** [comment]
you should use the unload methods instead.

**Comment by Shadowblitz16** [comment]
> you should use the unload methods instead.

This will allow users to use Dispose to unload and it will automatically cleanup resources when the class gets collected by the GC.

**Comment by MrScautHD** [comment]
> > you should use the unload methods instead.
> 
> This will allow users to use Dispose to unload and it will automatically cleanup resources when the class gets collected by the GC.

You use a contetmanager for that
