### ISSUE TITLE
[BUG] Inconsistent string type for Texture2D.Load()

### ISSUE THREAD

**Issue by Boyfinn** [MrScautHD/Raylib-CSharp#14]
**Describe the bug**
When loading an image to a Texture2D directly like so:
`_picture = Texture2D.Load(res/myimage.png);`
Results in:
`INFO: TEXTURE: [ID 3] Texture loaded successfully (256x256 | GRAY_ALPHA | 1 mipmaps)`
And works just fine.
However, passing a string type to the same method like so:
```
string _imagePath = "res/myimage.png";
_picture = Texture2D.Load(_imagePath!);
```
results in:
```
WARNING: FILEIO: File name provided is not valid
WARNING: FILEIO: [res/myimage.png] Failed to open file
```
SDK: Microsoft.NET.Sdk
Framework: net8.0

Raylib-CSharp:
nuget package
Version: 4.1.9

System:
OS: Linux Mint 21.3 x86_64
Kernel: 6.8.0-48-generic

**Comment by MrScautHD** [comment]
i think because you need todo `_picture = Texture2D.Load(_imagePath.Value!);`

**Comment by Boyfinn** [comment]
> i think because you need todo `_picture = Texture2D.Load(_imagePath.Value!);`

System.String doesn't have a member called "Value".

**Comment by Boyfinn** [comment]
This workaround works though: `_picture = Texture2D.Load($"{_picturePath!}");`

**Comment by MrScautHD** [comment]
i can not reproduce this

**Comment by MrScautHD** [comment]
it looks like a issue on your side.

**Comment by MrScautHD** [comment]
![grafik](https://github.com/user-attachments/assets/43e73ca3-3115-42b6-b704-fb0c1da4ede4)

**Comment by MrScautHD** [comment]
![grafik](https://github.com/user-attachments/assets/57f9acb1-e721-439b-8584-414218fa5cb5)

**Comment by MrScautHD** [comment]
Why do you place the `!` here? `_picture = Texture2D.Load(_imagePath!);` it means it could be null or what?

**Comment by Boyfinn** [comment]
> it looks like a issue on your side.

Looks like so. I removed and reinstalled the nuget packages and it works now. I used the ! guard just so that intellisense wouldnt complain about it not having an explicit safeguard.

**Comment by MrScautHD** [comment]
Glad yu fixed it!
