### ISSUE TITLE
[Feature] More formats for Image LoadFromMemory

### ISSUE THREAD

**Issue by Boyfinn** [MrScautHD/Raylib-CSharp#15]
I've tried loading images using `Image LoadFromMemory`, but it looks like only the .png format is supported. Are there any plans on adding more supported formats ?

**Comment by MrScautHD** [comment]
Hi!
Sry but that is a raylib issue. Not a raylib-csharp issue.

**Comment by Boyfinn** [comment]
> Hi! Sry but that is a raylib issue. Not a raylib-csharp issue.

How so? Formats like .bmp .tga and .jpg work fine on C and C++ raylib.

**Comment by MrScautHD** [comment]
Im just wrapping the methods, it is not possible that there is a issue on the C# side.
