### ISSUE TITLE
[BUG] Title bar not visible on ubuntu

### ISSUE THREAD

**Issue by Gukaboi** [MrScautHD/Raylib-CSharp#16]
After calling `Window.ToggleFullscreen()` post-initialization. The viewport is scaled into a window properly, but the title bar isn't visible.
This has also been tested on Windows, and LM22 with cinnamon, with both working as expected.

System:
Ubuntu 24.04.1 LTS x86_64
GNOME 46.0

**Comment by MrScautHD** [comment]
Hello, this is just a raylib wrapper.
You should report this bug to the C lib of Raylib.
