### ISSUE TITLE
[Feature] Sample projects

### ISSUE THREAD

**Issue by frankhaugen** [MrScautHD/Raylib-CSharp#6]
**Is your feature request related to a problem? Please describe.**
NO

**Describe the solution you'd like**
Under or nex to the directory "src" I'd like a "Samples" -directory, that can contain directories with projects with small or big samples, (community contributions to samples should be encuraged), as "Integration Tests"

**Describe alternatives you've considered**
Having "Integration Tests" which makes little sense

**Additional context**
A big arrow pointing for any burgeoning community to contribute in a way that will be both a "how to use" and serve as testing to prevent accidental breakages. It's hard to make targeted tests for a library like this, but making small games like Pong or Asteroids will cover a lot of functionality, and most likely be easy to make

**Comment by MrScautHD** [comment]
Hello!
Thats a great idea, i wanna doing that later. :)

**Comment by MrScautHD** [comment]
Added! :)
